language: objective-c
osx_image: xcode61
xcode_project: AeroGearPush.xcodeproj
xcode_scheme: AeroGearPush
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
