language: objective-c
osx_image: xcode7
xcode_workspace: AeroGearPush.xcworkspace
xcode_scheme: AeroGearPush
xcode_sdk: iphonesimulator

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
    - 1.x_dev
